BanqueTardiTP/BanqueTardi/Models/Operation.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BanqueTardi.Models
{
    public class Operation
    {
        [Key]
        public int OperationId { get; set; }

        [DisplayName("Compte")]
        public int TypeCompteID { get; set; }

        [DisplayName("Compte")]
        public int CompteId { get; set; }

        public Compte? Compte { get; set; }

        [Display(Name = "Date Operation")]
        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOperation { get; set; } = DateTime.Now;

        [Range(0, double.MaxValue, ErrorMessage = "L'opération ne peux pas avoir une valeur négatif")]
        [RegularExpression(@"^\d*$|(?=^.*$)^\d+\,\d{0,2}$")]
        public decimal Montant { get; set; }

        [Required(ErrorMessage = "Une description de l'opération est obligatoire")]
        public string Libelle { get; set; } = "";

        [Display(Name = "Type d'Opération")]
        public string TypeOperation { get; set; } = "";
    }
}

BanqueTardiTP/BanqueTardi/Controllers/OperationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BanqueTardi.Data;
using BanqueTardi.Models;
using System.Numerics;
using BanqueTardi.MVC.Interface;
using BanqueTardi.MVC.Services;

namespace BanqueTardi.Controllers
{
    public class OperationsController : Controller
    {
        private readonly ClientContext _context;
        private readonly List<string> TypeOperations = new() { "Débit", "Crédit" };
        private readonly IStorageServiceHelper _storageServiceHelper;

        public OperationsController(ClientContext context, IStorageServiceHelper storageServiceHelper)
        {
            _context = context;
            _storageServiceHelper = storageServiceHelper;
        }

        // GET: Operation/Historique
        public async Task<IActionResult> Historique(int? id, string? filtre) 
        {
            if (id == null || _context.Operations == null)
            {
                return NotFound();
            }

            ViewBag.Code = id;
            Compte? compte = await TrouverCompteAsync(id, false);
            if(compte == null)
            {
                return NotFound();
            }

            ViewBag.Id = compte.ClientId;
            IEnumerable<Operation> Operations = compte.Operations!;

            if (filtre != null)
                Operations = Operations.Where(n => n.TypeOperation.Contains(filtre, StringComparison.InvariantCultureIgnoreCase)).ToList();

            return View(Operations);
        }

        // GET: Operations/Create
        public async Task<IActionResult> Create(int? id)
        {
            ViewBag.TypeOperations = new SelectList(TypeOperations);
            ViewBag.CodeCourt = id;
            Compte? compte = await TrouverCompteAsync(id, false);
            if(compte == null)
            {
                return NotFound();
            }

            ViewBag.Id = compte.ClientId;
            if (ViewData["TypeOperations"] == null || id is null)
            {
                return NotFound();
            }

            return View();
        }

        // POST: Operations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id, [Bind("OperationId,Montant,Libelle,TypeOperation")] Operation operation)
        {
            if (!TypeOperations.Contains(operation.TypeOperation))
            {
                ModelState.AddModelError("TypeOperation", "Le type d'operation n'est pas valide.");
            }

            if (ModelState.IsValid)
            {
                Compte? compte = await TrouverCompteAsync(id);
                if(compte == null)
                {
                    return NotFound();
                }
                
                operation.TypeCompteID = compte.TypeCompteID;
                operation.CompteId = compte.CompteId;
                operation.DateOperation = DateTime.Now;

                if (compte.Solde < operation.Montant && operation.TypeOperation=="Débit")   
                {
                    if (operation.TypeCompteID == 10)
                    {
                        compte.Solde -= 10;
                        compte.Client!.NbDecouverts++;
                        Operation decouvert = new() {CompteId = compte.CompteId, TypeCompteID = compte.TypeCompteID,  Montant = 10m, Libelle = "Découvert", TypeOperation = "Débit", DateOperation=DateTime.Now };
                        _context.Add(decouvert);
                        string messageQueue = $"Découvert sur le compte bancaire {compte.CompteId}, du client {compte.Client.Nom} d'un montant {10m}$";
                        _storageServiceHelper.EnregistrerMessage(messageQueue, "queuedecouvert");
                    }
                    else if (operation.TypeCompteID != 10)
                    {
                        ModelState.AddModelError("Montant", "Vous ne pouvez avoir de découvert sur ce type de compte.");
                        ViewBag.TypeOperations = new SelectList(TypeOperations);
                        ViewBag.CodeCourt = id;
                        return View(operation);
                    }
                }

                //Mise à jour du solde
                if (operation.TypeOperation == "Débit")
                    compte.Solde -= operation.Montant;
                else 
                    compte.Solde += operation.Montant;

                _context.Update(compte);
                _context.Add(operation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Gerer", "Clients", new { id = compte!.ClientId });
            }

            ViewBag.TypeOperations = new SelectList(TypeOperations);
            ViewBag.CodeCourt = id;
            return View(operation);
        }     

        private async Task<bool> OperationExists(int id)
        {
          return await _context.Operations.AnyAsync(e => e.OperationId == id);
        }

        private async Task<Compte?> TrouverCompteAsync(int? Code, bool track = true)
        {
            if (Code == null)
            {
                return null;
            }
            int type = int.Parse(Code.ToString()!.Substring(0, 2));
            int compteId = int.Parse(Code.ToString()!.Substring(2));
            Compte? compte = null;
            if (track)
            {
                compte = await _context.Comptes
                .Where(c => c.TypeCompteID == type)
                .Where(c => c.CompteId == compteId)
                .Include(c => c.Operations)
                .Include(c => c.Client)
                .FirstOrDefaultAsync();
            } else
            {
                compte = await _context.Comptes
                .Where(c => c.TypeCompteID == type)
                .Where(c => c.CompteId == compteId)
                .Include(c => c.Operations)
                .Include(c => c.Client)
                .AsNoTrackingWithIdentityResolution()
                .FirstOrDefaultAsync();
            }
            return compte;
        }
    }
}

BanqueTardiTP/BanqueTardi/Views/Operations/Create.cshtml
@model BanqueTardi.Models.Operation

@{
    ViewData["Title"] = "Création d'Opérations";
}

<h1>Opération</h1>

<h4>Nouvelle opération compte : </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TypeOperation" class="control-label"></label>
                <select asp-for="TypeOperation" class="form-control" asp-items="ViewBag.TypeOperations"></select>
            </div>
            <div class="form-group">
                <label asp-for="Montant" class="control-label"></label>
                <input asp-for="Montant" class="form-control" />
                <span asp-validation-for="Montant" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Libelle" class="control-label"></label>
                <input asp-for="Libelle" class="form-control" />
                <span asp-validation-for="Libelle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Enregistrer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Clients" asp-action="Gerer" asp-route-id="@ViewBag.Id">Retour vers Gérer</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BanqueTardiTP/BanqueTardi/Views/Operations/Historique.cshtml
@model IEnumerable<BanqueTardi.Models.Operation>

@{
    ViewData["Title"] = "Historique d'Opérations";
}

<h1>Liste d'Opération</h1>
<hr />
<h2>Pour le compte @ViewBag.Code</h2>
<form asp-action="Historique" asp-controller="Operations">
            <div class="row g-2 align-items-center">
                <div class="col-auto">
                    <input class="form-control" type="text" id="filtre" name="filtre" />
                </div>
                <div class="col-auto">
                    <input class="btn btn-primary" type="submit" value="Recherche par Type d'opération" />
                </div>
            </div>
        </form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Montant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Libelle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TypeOperation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@if(Model is not null) {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Montant)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Libelle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypeOperation)
                </td>
            </tr>
        }
    } else {
        <tr>
            <td colspan="3"><h1>Aucune Opération</h1></td>
        </tr>
    }
    </tbody>
</table>
<a asp-controller="Clients" asp-action="Gerer" asp-route-id="@ViewBag.Id">Retour vers Gérer</a>